### ISSUE TITLE
ldapperf segfaults when using -r option

### ISSUE THREAD

**Issue by cwaldbieser** [arr2036/ldapperf#5]
GDB output below.
The file "netids.txt" has 1000 uids, one per line.

    [waldbiec@odin ldapperf]$ gdb ./ldapperf 
    GNU gdb (GDB) Fedora (7.3.50.20110722-16.fc16)
    Copyright (C) 2011 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-redhat-linux-gnu".
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>...
    Reading symbols from /home/waldbiec/projects/git-survey/ldapperf/ldapperf...(no debugging symbols found)...done.
    (gdb) run -b $BASE_DN -s sub -S -H ldaps://$HOST -D $BIND_DN -w $PASSWORD -r ./netids.txt -f '(uid=@)'
    Starting program: /home/waldbiec/projects/git-survey/ldapperf/ldapperf -b $BASE_DN -s sub -S -H ldaps://l$HOST -D $BIND_DN -w $PASSWORD -r ./netids.txt -f '(uid=@)'
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib64/libthread_db.so.1".
    Performing 50 search(es) total, with 5 threads, with persistent connections
    [New Thread 0x7ffff773c700 (LWP 43952)]
    [New Thread 0x7ffff6f3b700 (LWP 43953)]
    [New Thread 0x7ffff673a700 (LWP 43954)]
    [New Thread 0x7ffff5f39700 (LWP 43955)]
    [New Thread 0x7ffff5738700 (LWP 43956)]
    [Thread 0x7ffff773c700 (LWP 43952) exited]
    [Thread 0x7ffff5f39700 (LWP 43955) exited]
    [Thread 0x7ffff6f3b700 (LWP 43953) exited]
    [Thread 0x7ffff673a700 (LWP 43954) exited]
    [Thread 0x7ffff5738700 (LWP 43956) exited]

    Program received signal SIGSEGV, Segmentation fault.
    0x000000376b07dd55 in malloc_consolidate (av=0x376b3b1700) at malloc.c:4266
    4266		      unlink(av, nextchunk, bck, fwd);
    (gdb)

**Comment by arr2036** [comment]
backtrace please?

**Comment by cwaldbieser** [comment]
I changed the makefile to pass -g3 to cc.  I get the following extra:

    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib64/libthread_db.so.1".
    Performing 50 search(es) total, with 5 threads, with persistent connections
    [New Thread 0x7ffff773c700 (LWP 44429)]
    [New Thread 0x7ffff6f3b700 (LWP 44430)]
    [New Thread 0x7ffff673a700 (LWP 44431)]
    [New Thread 0x7ffff5f39700 (LWP 44432)]
    [New Thread 0x7ffff5738700 (LWP 44433)]
    [Thread 0x7ffff773c700 (LWP 44429) exited]
    [Thread 0x7ffff6f3b700 (LWP 44430) exited]
    [Thread 0x7ffff5738700 (LWP 44433) exited]
    [Thread 0x7ffff5f39700 (LWP 44432) exited]
    *** glibc detected *** /home/waldbiec/projects/git-survey/ldapperf/ldapperf: free(): invalid pointer: 0x0000000000609340 ***
    [Thread 0x7ffff673a700 (LWP 44431) exited]
    ======= Backtrace: =========
    /lib64/libc.so.6[0x376b07da76]
    /home/waldbiec/projects/git-survey/ldapperf/ldapperf[0x40191f]
    /home/waldbiec/projects/git-survey/ldapperf/ldapperf[0x402faa]
    /lib64/libc.so.6(__libc_start_main+0xed)[0x376b02169d]
    /home/waldbiec/projects/git-survey/ldapperf/ldapperf[0x401329]
    ======= Memory map: ========
    00400000-00405000 r-xp 00000000 fd:02 20711524                           /home/waldbiec/projects/git-survey/ldapperf/ldapperf
    00604000-00605000 rw-p 00004000 fd:02 20711524                           /home/waldbiec/projects/git-survey/ldapperf/ldapperf
    00605000-00626000 rw-p 00000000 00:00 0                                  [heap]
    33bc200000-33bc219000 r-xp 00000000 fd:01 176819                         /usr/lib64/libsasl2.so.2.0.23
    33bc219000-33bc419000 ---p 00019000 fd:01 176819                         /usr/lib64/libsasl2.so.2.0.23
    33bc419000-33bc41a000 r--p 00019000 fd:01 176819                         /usr/lib64/libsasl2.so.2.0.23
    33bc41a000-33bc41b000 rw-p 0001a000 fd:01 176819                         /usr/lib64/libsasl2.so.2.0.23
    376ac00000-376ac22000 r-xp 00000000 fd:01 163297                         /lib64/ld-2.14.90.so
    376ae21000-376ae22000 r--p 00021000 fd:01 163297                         /lib64/ld-2.14.90.so
    376ae22000-376ae23000 rw-p 00022000 fd:01 163297                         /lib64/ld-2.14.90.so
    376ae23000-376ae24000 rw-p 00000000 00:00 0 
    376b000000-376b1ad000 r-xp 00000000 fd:01 163299                         /lib64/libc-2.14.90.so
    376b1ad000-376b3ad000 ---p 001ad000 fd:01 163299                         /lib64/libc-2.14.90.so
    376b3ad000-376b3b1000 r--p 001ad000 fd:01 163299                         /lib64/libc-2.14.90.so
    376b3b1000-376b3b3000 rw-p 001b1000 fd:01 163299                         /lib64/libc-2.14.90.so
    376b3b3000-376b3b8000 rw-p 00000000 00:00 0 
    376b400000-376b402000 r-xp 00000000 fd:01 168111                         /lib64/libdl-2.14.90.so
    376b402000-376b602000 ---p 00002000 fd:01 168111                         /lib64/libdl-2.14.90.so
    376b602000-376b603000 r--p 00002000 fd:01 168111                         /lib64/libdl-2.14.90.so
    376b603000-376b604000 rw-p 00003000 fd:01 168111                         /lib64/libdl-2.14.90.so
    376b800000-376b817000 r-xp 00000000 fd:01 142966                         /lib64/libpthread-2.14.90.so
    376b817000-376ba16000 ---p 00017000 fd:01 142966                         /lib64/libpthread-2.14.90.so
    376ba16000-376ba17000 r--p 00016000 fd:01 142966                         /lib64/libpthread-2.14.90.so
    376ba17000-376ba18000 rw-p 00017000 fd:01 142966                         /lib64/libpthread-2.14.90.so
    376ba18000-376ba1c000 rw-p 00000000 00:00 0 
    376bc00000-376bc07000 r-xp 00000000 fd:01 168116                         /lib64/librt-2.14.90.so
    376bc07000-376be06000 ---p 00007000 fd:01 168116                         /lib64/librt-2.14.90.so
    376be06000-376be07000 r--p 00006000 fd:01 168116                         /lib64/librt-2.14.90.so
    376be07000-376be08000 rw-p 00007000 fd:01 168116                         /lib64/librt-2.14.90.so
    376c000000-376c015000 r-xp 00000000 fd:01 168112                         /lib64/libgcc_s-4.6.3-20120306.so.1
    376c015000-376c214000 ---p 00015000 fd:01 168112                         /lib64/libgcc_s-4.6.3-20120306.so.1
    376c214000-376c215000 rw-p 00014000 fd:01 168112                         /lib64/libgcc_s-4.6.3-20120306.so.1
    376dc00000-376dc18000 r-xp 00000000 fd:01 168126                         /lib64/libresolv-2.14.90.so
    376dc18000-376de18000 ---p 00018000 fd:01 168126                         /lib64/libresolv-2.14.90.so
    376de18000-376de19000 r--p 00018000 fd:01 168126                         /lib64/libresolv-2.14.90.so
    376de19000-376de1a000 rw-p 00019000 fd:01 168126                         /lib64/libresolv-2.14.90.so
    376de1a000-376de1c000 rw-p 00000000 00:00 0 
    377dc00000-377dc9b000 r-xp 00000000 fd:01 168171                         /usr/lib64/libsqlite3.so.0.8.6
    377dc9b000-377de9a000 ---p 0009b000 fd:01 168171                         /usr/lib64/libsqlite3.so.0.8.6
    377de9a000-377de9c000 r--p 0009a000 fd:01 168171                         /usr/lib64/libsqlite3.so.0.8.6
    377de9c000-377de9e000 rw-p 0009c000 fd:01 168171                         /usr/lib64/libsqlite3.so.0.8.6
    377de9e000-377de9f000 rw-p 00000000 00:00 0 
    3a8b400000-3a8b408000 r-xp 00000000 fd:01 166717                         /lib64/libcrypt-2.14.90.so
    3a8b408000-3a8b607000 ---p 00008000 fd:01 166717                         /lib64/libcrypt-2.14.90.so
    3a8b607000-3a8b608000 r--p 00007000 fd:01 166717                         /lib64/libcrypt-2.14.90.so
    3a8b608000-3a8b609000 rw-p 00008000 fd:01 166717                         /lib64/libcrypt-2.14.90.so
    3a8b609000-3a8b637000 rw-p 00000000 00:00 0 
    3a8b800000-3a8b863000 r-xp 00000000 fd:01 168607                         /lib64/libfreebl3.so
    3a8b863000-3a8ba62000 ---p 00063000 fd:01 168607                         /lib64/libfreebl3.so
    3a8ba62000-3a8ba64000 rw-p 00062000 fd:01 168607                         /lib64/libfreebl3.so
    3a8ba64000-3a8ba68000 rw-p 00000000 00:00 0 
    3a8bc00000-3a8bc04000 r-xp 00000000 fd:01 169077                         /lib64/libplc4.so
    3a8bc04000-3a8be03000 ---p 00004000 fd:01 169077                         /lib64/libplc4.so
    3a8be03000-3a8be04000 r--p 00003000 fd:01 169077                         /lib64/libplc4.so
    3a8be04000-3a8be05000 rw-p 00004000 fd:01 169077                         /lib64/libplc4.so
    3a8c000000-3a8c039000 r-xp 00000000 fd:01 168537                         /lib64/libnspr4.so
    3a8c039000-3a8c238000 ---p 00039000 fd:01 168537                         /lib64/libnspr4.so
    3a8c238000-3a8c239000 r--p 00038000 fd:01 168537                         /lib64/libnspr4.so
    3a8c239000-3a8c23b000 rw-p 00039000 fd:01 168537                         /lib64/libnspr4.so
    3a8c23b000-3a8c23d000 rw-p 00000000 00:00 0 
    3a8c400000-3a8c403000 r-xp 00000000 fd:01 169078                         /lib64/libplds4.so
    3a8c403000-3a8c602000 ---p 00003000 fd:01 169078                         /lib64/libplds4.so
    3a8c602000-3a8c603000 r--p 00002000 fd:01 169078                         /lib64/libplds4.so
    3a8c603000-3a8c604000 rw-p 00003000 fd:01 169078                         /lib64/libplds4.so
    3a8c800000-3a8c931000 r-xp 00000000 fd:01 168246                         /usr/lib64/libnss3.so
    3a8c931000-3a8cb30000 ---p 00131000 fd:01 168246                         /usr/lib64/libnss3.so
    Program received signal SIGABRT, Aborted.
    0x000000376b036285 in __GI_raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
    64	  return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
    Missing separate debuginfos, use: debuginfo-install libgcc-4.6.3-2.fc16.x86_64
    (gdb)

**Comment by arr2036** [comment]
run ``bt`` from the gdb prompt.

**Comment by arr2036** [comment]
Thanks. Pushed a couple of minor fixes, might solve it.

**Comment by cwaldbieser** [comment]
Still not working.  I think that the problem is in `lp_names_file()`:

    if (idx == cnt) {
        cnt += 1000;
        names = realloc(names, (sizeof(lp_name_t) * cnt) + 1);
    }

I think you are allocating the size of an `lp_name_t`* the count, plus **one byte**.  I think you want to  do this:

    if (idx == cnt) {
        cnt += 1000;
        names = realloc(names, (sizeof(lp_name_t) * (cnt + 1));
    }

That is the (size of the struct) * (the count + 1).  That way you have the extra struct at the end that you can set NULL fields in.

**Comment by cwaldbieser** [comment]
I compiled the above change and that seems to work.  Sorry, I was too lazy to fork and do a PR.

**Comment by arr2036** [comment]
Thanks!
